"""Second half of the command table: operator/runtime/multi-agent/approvals.

See :mod:`cli.command_specs` for the ``CommandSpec`` dataclass and the first
half of the table, and :mod:`cli.command_registry` for the public API and
the full purity contract these tables share.
"""
from __future__ import annotations

from .command_specs import CommandSpec, PHASE_PRE_DOTENV


COMMANDS_OPS: tuple[CommandSpec, ...] = (
    # ── Operator status, audits & readiness ──────────────────
    CommandSpec(
        canonical=":architecture-audit",
        description="inspect layers and multi-agent gaps",
        category="Operator status, audits & readiness",
        handler_key="architecture_audit",
        aliases=(":arch-audit", ":roadmap-audit",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":operator-check",
        description="conversational project/status digest",
        category="Operator status, audits & readiness",
        handler_key="operator_check",
        aliases=(":project-check", ":project-status",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":urgent-status",
        description="approvals + queue + scheduler urgency digest",
        category="Operator status, audits & readiness",
        handler_key="urgent_status",
        aliases=(":operator-urgent",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":next-actions",
        description="architecture priorities + recommendations",
        category="Operator status, audits & readiness",
        handler_key="next_actions",
        aliases=(":operator-next",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":autonomy-readiness",
        description="whether autonomy is safe to run now",
        category="Operator status, audits & readiness",
        handler_key="autonomy_readiness",
        aliases=(":operator-readiness",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":dry-health-pass",
        description="local read-only autonomous health panel",
        category="Operator status, audits & readiness",
        handler_key="dry_health_pass",
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":coding-readiness",
        description="safe programming task readiness report",
        category="Operator status, audits & readiness",
        handler_key="coding_readiness",
        aliases=(":programming-readiness",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":operator-task",
        description="one safe multi-line operator task report",
        category="Operator status, audits & readiness",
        handler_key="operator_task",
        usage="<…>",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":learn",
        description="plan sources, then ingest selected learning set",
        category="Operator status, audits & readiness",
        handler_key="learn",
        aliases=(":learn-project",),
        usage="[goal] [flags]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":conflicts",
        description="inspect source claim conflicts and suggestions",
        category="Operator status, audits & readiness",
        handler_key="conflicts",
        aliases=(":conflict-status",),
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":state-store-drill",
        description="prove JSONL quarantine/recovery on an isolated file",
        category="Operator status, audits & readiness",
        handler_key="state_store_drill",
        aliases=(":state-drill", ":state-recovery-drill",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":release-audit",
        description="inspect release artifact hygiene exclusions",
        category="Operator status, audits & readiness",
        handler_key="release_audit",
        aliases=(":release-hygiene",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":supply-chain-audit",
        description="inspect pinned deps and CI release gates",
        category="Operator status, audits & readiness",
        handler_key="supply_chain_audit",
        aliases=(":supply-audit", ":ci-audit",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":best-next-action",
        description="choose the single most important next action (advisory)",
        category="Operator status, audits & readiness",
        handler_key="best_next_action",
        aliases=(":next-action", ":bna",),
        usage="[--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":assumptions",
        description="show the last 20 logged planning assumptions",
        category="Operator status, audits & readiness",
        handler_key="assumptions",
        aliases=(":assumption-log",),
        usage="[--json]",
    ),
    # ── Autonomous runtime, tasks & scheduling ────────────────
    CommandSpec(
        canonical=":auto-run",
        description="bounded autonomous health pass",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="auto_run",
        usage="[goal] [flags]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":work-session",
        description="bounded multi-cycle session with time budget",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="work_session",
        aliases=(":work-sess",),
        usage="[goal] [flags]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":campaign-start",
        description="budgeted autonomous campaign with per-cycle ledger",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="campaign_start",
        aliases=(":campaign",),
        usage="[goal] [flags]",
    ),
    CommandSpec(
        canonical=":campaign-status",
        description="read the campaign ledger digest (no budget spent)",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="campaign_status",
        aliases=(":campaign-ledger",),
    ),
    CommandSpec(
        canonical=":capability-request",
        description="Propose a capability request.",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="capability_request",
        aliases=(":capability-proposal",),
        usage="<goal> [--submit] [--json]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":auto-status",
        description="inspect autonomous runtime inbox/status",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="auto_status",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":queue-status",
        description="inspect runtime task queue summary",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="queue_status",
    ),
    CommandSpec(
        canonical=":scheduler-status",
        description="inspect scheduler summary",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="scheduler_status",
    ),
    CommandSpec(
        canonical=":task-add",
        description="enqueue persistent autonomous task",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="task_add",
        usage="[goal] [flags]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":task-list",
        description="list runtime tasks",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="task_list",
        usage="[status|all]",
    ),
    CommandSpec(
        canonical=":task-run",
        description="run due pending runtime task(s)",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="task_run",
    ),
    CommandSpec(
        canonical=":task-cancel",
        description="cancel one queued task",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="task_cancel",
        usage="<task_id>",
    ),
    CommandSpec(
        canonical=":task-unblock",
        description="return an approval-blocked task to pending",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="task_unblock",
        usage="<task_id>",
    ),
    CommandSpec(
        canonical=":schedule-add",
        description="create recurring scheduler entry",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="schedule_add",
        usage="<min> <goal>",
    ),
    CommandSpec(
        canonical=":schedule-list",
        description="list schedules",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="schedule_list",
        usage="[status|all]",
    ),
    CommandSpec(
        canonical=":schedule-disable",
        description="disable a runtime schedule without running it",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="schedule_disable",
        usage="<id>",
        in_startup_summary=True,
        phase=PHASE_PRE_DOTENV,
    ),
    CommandSpec(
        canonical=":schedule-tick",
        description="enqueue due schedule tasks, optionally run them",
        category="Autonomous runtime, tasks & scheduling",
        handler_key="schedule_tick",
        usage="[--run]",
        in_startup_summary=True,
    ),
    # ── Multi-agent / subagents (bounded — see governance doc) ────
    CommandSpec(
        canonical=":team-plan",
        description="dry-run bounded subagent contracts",
        category="Multi-agent / subagents (bounded — see governance doc)",
        handler_key="team_plan",
        aliases=(":agent-team", ":subagents",),
        usage="<goal>",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":subagent-proposal",
        description="autonomous subagent initiative proposal",
        category="Multi-agent / subagents (bounded — see governance doc)",
        handler_key="subagent_proposal",
        aliases=(":propose-subagent",),
        usage="<…>",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":team-run",
        description="dry-run execution walk over subagent contracts",
        category="Multi-agent / subagents (bounded — see governance doc)",
        handler_key="team_run",
        aliases=(":team-execute", ":subagents-run",),
        usage="<goal>",
        in_startup_summary=True,
    ),
    # ── Approvals & alerts ───────────────────────────
    CommandSpec(
        canonical=":approval-list",
        description="list pending/approved/denied approval items",
        category="Approvals & alerts",
        handler_key="approval_list",
        usage="[state]",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":approval-triage",
        description="read-only triage: clusters/duplicates/stale + advice",
        category="Approvals & alerts",
        handler_key="approval_triage",
        aliases=(":triage",),
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":ack",
        description="acknowledge an advisory alert so it stops dominating BNA",
        category="Approvals & alerts",
        handler_key="ack",
        aliases=(":acknowledge",),
        usage="<action>",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":ack-list",
        description="list active acknowledgements",
        category="Approvals & alerts",
        handler_key="ack_list",
        aliases=(":acks",),
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":ack-clear",
        description="restore an acknowledged alert to the top-pick race",
        category="Approvals & alerts",
        handler_key="ack_clear",
        aliases=(":unack",),
        usage="<action>",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":inbox",
        description="shortcut: list pending approvals",
        category="Approvals & alerts",
        handler_key="inbox",
    ),
    CommandSpec(
        canonical=":approve",
        description="shortcut: :approval-approve",
        category="Approvals & alerts",
        handler_key="approve",
        usage="<id>",
    ),
    CommandSpec(
        canonical=":deny",
        description="shortcut: :approval-deny",
        category="Approvals & alerts",
        handler_key="deny",
        usage="<id>",
    ),
    CommandSpec(
        canonical=":approval-approve",
        description="mark an approval inbox item approved",
        category="Approvals & alerts",
        handler_key="approval_approve",
        usage="<id>",
    ),
    CommandSpec(
        canonical=":approval-deny",
        description="mark an approval inbox item denied",
        category="Approvals & alerts",
        handler_key="approval_deny",
        usage="<id>",
    ),
    CommandSpec(
        canonical=":approval-run",
        description="execute one approved whitelisted operation",
        category="Approvals & alerts",
        handler_key="approval_run",
        usage="<id>",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":approval-abort",
        description="mark an approval inbox item aborted",
        category="Approvals & alerts",
        handler_key="approval_abort",
        usage="<id>",
    ),
    # ── Help ──────────────────────────────────────────────
    CommandSpec(
        canonical=":help",
        description="show this command help",
        category="Help",
        handler_key="help",
        in_startup_summary=True,
    ),
    CommandSpec(
        canonical=":quit",
        description="exit",
        category="Help",
        handler_key="quit",
        aliases=(":exit",),
        in_startup_summary=True,
    ),
)
