"""Generate the issue tally from the registry's own sections.

The tally was maintained by hand and was wrong three times in one working
session: two off-by-one list/count mismatches, and finally a document that
claimed "50 issues total — this tally is the authoritative count" four lines
below "Total is now 53". A source of truth that contradicts itself is worse
than no source of truth, because it is quoted with confidence.

So the count is derived, never typed. Each issue's own `**Status:**` line is
the input; the header table is output.

    python scripts/registry_tally.py --check    verify (exit 1 on drift)
    python scripts/registry_tally.py --write    regenerate the table

`### MIR-external-checklist` is deliberately excluded from the issue count: it
is a checklist of externally-observed failure modes, explicitly not confirmed
repo defects, and counting it as an issue is what made the totals ambiguous.
It is reported separately.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

REGISTRY = Path(__file__).resolve().parents[1] / "docs" / "audit" / "MASTER_ISSUE_REGISTRY.md"

_HEADING = re.compile(r"^### MIR-(\S+)", re.M)
_STATUS = re.compile(r"\*\*Status:\*\*\s*\**`([a-z_]+)`")
_TABLE = re.compile(
    r"(?P<start>### Status tally\n\n)"
    # No re.S, and [^\n]* rather than .* — with DOTALL this pattern swallowed
    # the entire rest of the document (765 lines), and --write would have
    # destroyed the registry it exists to protect.
    r"(?P<table>(?:\|[^\n]*\n)+)"
)


def parse(text: str) -> tuple[dict[str, list[str]], list[str]]:
    """Return {status: [issue ids]} plus any sections missing a status line."""
    parts = re.split(r"^(### MIR-\S+)", text, flags=re.M)
    by_status: dict[str, list[str]] = {}
    unparsed: list[str] = []
    for head, body in zip(parts[1::2], parts[2::2]):
        ident = _HEADING.match(head).group(1)
        if not ident.isdigit():
            continue                      # the external checklist is not an issue
        match = _STATUS.search(body)
        if match is None:
            unparsed.append(ident)
            continue
        by_status.setdefault(match.group(1), []).append(ident)
    return by_status, unparsed


def render(by_status: dict[str, list[str]]) -> str:
    total = sum(len(v) for v in by_status.values())
    rows = ["| Status | Count | IDs |", "|---|---|---|"]
    for status in sorted(by_status, key=lambda s: (-len(by_status[s]), s)):
        ids = ", ".join(f"MIR-{i}" for i in sorted(by_status[status]))
        rows.append(f"| {status} | {len(by_status[status])} | {ids} |")
    rows.append(f"| **TOTAL** | **{total}** | generated by `scripts/registry_tally.py` |")
    return "\n".join(rows) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args(argv)

    text = REGISTRY.read_text(encoding="utf-8")
    by_status, unparsed = parse(text)
    total = sum(len(v) for v in by_status.values())

    if unparsed:
        print(f"ERROR: sections without a parseable Status: {unparsed}", file=sys.stderr)
        return 1

    table = render(by_status)
    match = _TABLE.search(text)
    if match is None:
        print("ERROR: could not locate the '### Status tally' table", file=sys.stderr)
        return 1

    if args.write:
        REGISTRY.write_text(
            text[: match.start("table")] + table + text[match.end("table") :],
            encoding="utf-8",
        )
        print(f"tally rewritten: {total} issues across {len(by_status)} statuses")
        return 0

    current = match.group("table")
    if current.strip() != table.strip():
        print("REGISTRY TALLY OUT OF SYNC", file=sys.stderr)
        print("--- declared ---", file=sys.stderr)
        print(current, file=sys.stderr)
        print("--- derived ---", file=sys.stderr)
        print(table, file=sys.stderr)
        return 1
    print(f"tally in sync: {total} issues, {dict(Counter({k: len(v) for k, v in by_status.items()}))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
